export class Actions {

    static UNAUTHORIZED_FAILURE = 'UNAUTHORIZED_FAILURE';

    static GET_POSTS_SUCCESS_UPDATE = 'GET_POSTS_SUCCESS_UPDATE';
    static GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
    static GET_POSTS_LOADING = 'GET_POSTS_LOADING';
    static GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

    static GET_JOIN_REQUESTS_SUCCESS_UPDATE = 'GET_JOIN_REQUESTS_SUCCESS_UPDATE';
    static GET_JOIN_REQUESTS_SUCCESS = 'GET_JOIN_REQUESTS_SUCCESS';
    static GET_JOIN_REQUESTS_LOADING = 'GET_JOIN_REQUESTS_LOADING';
    static GET_JOIN_REQUESTS_IGNORE_LOADING = 'GET_JOIN_REQUESTS_IGNORE_LOADING';
    static GET_JOIN_REQUESTS_CONFIRM_LOADING = 'GET_JOIN_REQUESTS_CONFIRM_LOADING';
    static GET_JOIN_REQUESTS_FAILURE = 'GET_JOIN_REQUESTS_FAILURE';
    static GET_JOIN_REQUESTS_FAILURE = 'GET_JOIN_REQUESTS_IGNORE_FAILURE';
    static GET_JOIN_REQUESTS_FAILURE = 'GET_JOIN_REQUESTS_CONFIRM_FAILURE';

    static GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS';
    static GET_ADVERTS_LOADING = 'GET_ADVERTS_LOADING';
    static GET_ADVERTS_FAILURE = 'GET_ADVERTS_FAILURE';

    static GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
    static GET_EVENTS_LOADING = 'GET_EVENTS_LOADING';
    static GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

    static GET_FUTURE_EVENTS_SUCCESS = 'GET_FUTURE_EVENTS_SUCCESS';
    static GET_FUTURE_EVENTS_LOADING = 'GET_FUTURE_EVENTS_LOADING';
    static GET_FUTURE_EVENTS_FAILURE = 'GET_FUTURE_EVENTS_FAILURE';

    static GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
    static GET_FAVORITES_LOADING = 'GET_FAVORITES_LOADING';
    static GET_FAVORITES_FAILURE = 'GET_FAVORITES_FAILURE';

    static GET_SAVES_SUCCESS = 'GET_SAVES_SUCCESS';
    static GET_SAVES_LOADING = 'GET_SAVES_LOADING';
    static GET_SAVES_FAILURE = 'GET_SAVES_FAILURE';

    static GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
    static GET_CHANNELS_LOADING = 'GET_CHANNELS_LOADING';
    static GET_CHANNELS_FAILURE = 'GET_CHANNELS_FAILURE';

    static GET_SHARES_SUCCESS = 'GET_SHARES_SUCCESS';
    static GET_SHARES_LOADING = 'GET_SHARES_LOADING';
    static GET_SHARES_FAILURE = 'GET_SHARES_FAILURE';

    static GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
    static GET_STORIES_LOADING = 'GET_STORIES_LOADING';
    static GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';

    static GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
    static GET_BLOGS_LOADING = 'GET_BLOGS_LOADING';
    static GET_BLOGS_FAILURE = 'GET_BLOGS_FAILURE';

    static GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
    static GET_COMMENTS_LOADING = 'GET_COMMENTS_LOADING';
    static GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

    static ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
    static ADD_COMMENT_LOADING = 'ADD_COMMENT_LOADING';
    static ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

    static EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
    static EDIT_COMMENT_LOADING = 'EDIT_COMMENT_LOADING';
    static EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';

    static DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
    static DELETE_COMMENT_LOADING = 'DELETE_COMMENT_LOADING';
    static DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

    static GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS';
    static GET_REPLIES_LOADING = 'GET_REPLIES_LOADING';
    static GET_REPLIES_FAILURE = 'GET_REPLIES_FAILURE';

    static ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
    static ADD_REPLY_LOADING = 'ADD_REPLY_LOADING';
    static ADD_REPLY_FAILURE = 'ADD_REPLY_FAILURE';

    static EDIT_REPLY_SUCCESS = 'EDIT_REPLY_SUCCESS';
    static EDIT_REPLY_LOADING = 'EDIT_REPLY_LOADING';
    static EDIT_REPLY_FAILURE = 'EDIT_REPLY_FAILURE';

    static DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS';
    static DELETE_REPLY_LOADING = 'DELETE_REPLY_LOADING';
    static DELETE_REPLY_FAILURE = 'DELETE_REPLY_FAILURE';

    static GET_CHANNEL_SUCCESS = 'GET_CHANNEL_SUCCESS';
    static GET_CHANNEL_LOADING = 'GET_CHANNEL_LOADING';
    static GET_CHANNEL_FAILURE = 'GET_CHANNEL_FAILURE';

    static CHANGE_SUBSCRIBTION_STATUS_LOADING = 'CHANGE_SUBSCRIBTION_STATUS_LOADING';
    static CHANGE_SUBSCRIBTION_STATUS_SUCCESS = 'CHANGE_SUBSCRIBTION_STATUS_SUCCESS';
    static CHANGE_SUBSCRIBTION_STATUS_FAILURE = 'CHANGE_SUBSCRIBTION_STATUS_FAILURE';

    static CHANGE_JOIN_STATUS_LOADING = 'CHANGE_JOIN_STATUS_LOADING';
    static CHANGE_JOIN_STATUS_SUCCESS = 'CHANGE_JOIN_STATUS_SUCCESS';
    static CHANGE_JOIN_STATUS_FAILURE = 'CHANGE_JOIN_STATUS_FAILURE';

    static DELETE_CONTENT_LOADING = 'DELETE_CONTENT_LOADING';
    static DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS';
    static DELETE_CONTENT_FAILURE = 'DELETE_CONTENT_FAILURE';
    static DELETE_CONTENT_INITIAL = 'DELETE_CONTENT_INITIAL';

    static ADVERT_INTERACTION_LOADING = 'ADVERT_INTERACTION_LOADING';
    static ADVERT_INTERACTION_SUCCESS = 'ADVERT_INTERACTION_SUCCESS';
    static ADVERT_INTERACTION_FAILURE = 'ADVERT_INTERACTION_FAILURE';
    static ADVERT_INTERACTION_INITIAL = 'ADVERT_INTERACTION_INITIAL';

    static BLOG_INTERACTION_LOADING = 'BLOG_INTERACTION_LOADING';
    static BLOG_INTERACTION_SUCCESS = 'BLOG_INTERACTION_SUCCESS';
    static BLOG_INTERACTION_FAILURE = 'BLOG_INTERACTION_FAILURE';
    static BLOG_INTERACTION_INITIAL = 'BLOG_INTERACTION_INITIAL';

    static EVENT_INTERACTION_LOADING = 'EVENT_INTERACTION_LOADING';
    static EVENT_INTERACTION_SUCCESS = 'EVENT_INTERACTION_SUCCESS';
    static EVENT_INTERACTION_FAILURE = 'EVENT_INTERACTION_FAILURE';
    static EVENT_INTERACTION_INITIAL = 'EVENT_INTERACTION_INITIAL';

    static POST_INTERACTION_LOADING = 'POST_INTERACTION_LOADING';
    static POST_INTERACTION_SUCCESS = 'POST_INTERACTION_SUCCESS';
    static POST_INTERACTION_FAILURE = 'POST_INTERACTION_FAILURE';
    static POST_INTERACTION_INITIAL = 'POST_INTERACTION_INITIAL';

    static STORY_INTERACTION_LOADING = 'STORY_INTERACTION_LOADING';
    static STORY_INTERACTION_SUCCESS = 'STORY_INTERACTION_SUCCESS';
    static STORY_INTERACTION_FAILURE = 'STORY_INTERACTION_FAILURE';
    static STORY_INTERACTION_INITIAL = 'STORY_INTERACTION_INITIAL';

    static GET_USER_SUCCESS = 'GET_USER_SUCCESS';
    static GET_USER_LOADING = 'GET_USER_LOADING';
    static GET_USER_FAILURE = 'GET_USER_FAILURE';

}

export class Operations {
    static CREATE = 'CREATE';
    static EDIT = 'EDIT';
    static REMOVE = 'REMOVE';
    static REJECT = 'REJECT';
    static CANCEL = 'CANCEL';
    static ACCEPT = 'ACCEPT';
    static LOGIN = 'LOGIN';
}